### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by stumpyuk1** [arkem/py360#1]
Running report360.py from current release, I encountered the following error:

---

XDBF (/FFFE07D1.gpd - 66)

---

Version: 65536
Entries: 66
Images: 2
Titles: 32
Strings: 1
Achievements: 0

SETTINGS
0x10040000 GPD Setting Permissions 8
0x100000000 GPD Setting 0x0
0x10040004 GPD Setting GamerZone Pro
0x10040005 GPD Setting Region Georgia
0x10040006 GPD Setting Gamerscore 1240
0x5004000b GPD Setting Reputation 58.7222862244
0x1004000d GPD Setting Voice Output Speakers 0
0x1004000e GPD Setting Voice Volume Setting 100
0x4064000f GPD Setting Gamer Picture Reference fffe08540001e5a500017575
    reporter.document_image()
  File "/opt/py360/report360.py", line 182, in document_image
    self.print_xdbf(g)
  File "/opt/py360/report360.py", line 94, in print_xdbf
    self.output("0x%x %s" % (idnum, str(sett)))
  File "/opt/py360/py360/xdbf.py", line 32, in **str**
    result.append(str(self.data))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa4' in position 0: ordinal not in range(128)

My kernel version:
Linux 3.0.0-25-generic #41-Ubuntu SMP Mon Aug 13 17:58:59 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

**Comment by arkem** [comment]
Thanks for the report, is it possible for you to send me the FFFE07D1.gpd file? Use something like "./mount.py360 myxboximage.bin /mnt/xbox" to mount the file system and find the file.

Errors like this are a known issue but part of the reason I haven't yet fixed them is that I don't have enough examples of the triggering conditions.
