### ISSUE TITLE
STFS.py not reading and writing binary

### ISSUE THREAD

**Issue by swingtempo** [arkem/py360#2]
I was trying to run STFS.py on a file I saved onto a USB drive. on my Win10 Python2.7.15 environment, the input and output both get truncated.  In particular the truncation happens in the header.

I have fixed in on a branch - essentially I needed to add 'b' in the open statements. Example:
self.fd = open(filename, 'r**b**')

Not sure you take contributions - can I submit a PR?

**Comment by arkem** [comment]
Good catch! I'd happily take your PR
